# Generated by Django 2.0.9 on 2018-11-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('order_date', models.DateTimeField()),
                ('customer_id', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
    ]
